### ISSUE TITLE
🐛 Error on Chromium-based browsers: "Uncaught (in promise) RangeError: WebAssembly.Compile is disallowed on the main thread"

### ISSUE THREAD

**Issue by garcia-alejandro** [NostrDevKit/nostr-js-example#1]
# Description:
I have discovered that the application is not functioning properly on Chromium-based browsers. The error message that I am encountering is: 

> "Uncaught (in promise) RangeError: WebAssembly.Compile is disallowed on the main thread, if the buffer size is larger than 4KB. Use WebAssembly.compile, or compile on a worker thread."

 It seems that the issue is related to the `"@rust-nostr/nostr"` library and WebAssembly. 

## 🔁 Steps to Reproduce:
1. Install the dependencies using the `package-lock.json`
2. Open the application on a `Chromium-based browser`.
3. Attempt to run the application.
4. Observe the error message: `"Uncaught (in promise) RangeError: WebAssembly.Compile is disallowed on the main thread, if the buffer size is larger than 4KB. Use WebAssembly.compile, or compile on a worker thread."`

## 💻 Actual Behavior:
The application throws an error message on Chromium-based browsers, preventing it from functioning correctly. The issue breaks the app when it is rendering

## ℹ️ Additional Information:

The issue is not present on Firefox.

**Comment by yukibtc** [comment]
Thanks for finding this bug.

The problem seems related to only to JS bindings: testing the same app using directly WASM (so no JS bindings) everything works (like I have done with `nostr-sdk-wasm-example`, it works both on firefox and chrome).

**Comment by yukibtc** [comment]
Now should be fixed, can you confirm?

**Comment by garcia-alejandro** [comment]
> Now should be fixed, can you confirm?

Yes, Now is working well. Thanks! 👍🏼
